### ISSUE TITLE
insteonplm_interactive: 2245 hub: Port issue

### ISSUE THREAD

**Issue by ttocsr** [nugget/python-insteonplm#198]
This python error is returned if you specify a port, even if it is the default port.  If you leave the port field blank you do not get this error.

`ValueError: Unknown format code 'd' for object of type 'str'`

This is the full session.
```
insteonplm: set_hub_connection hidden_username hidden_password 192.168.1.78 25105
insteonplm: connect
Connecting to Insteon Modem at 192.168.1.78
Task exception was never retrieved
future: <Task finished coro=<Commander._read_line() done, defined at /srv/homeassistant/lib/python3.7/site-packages/insteonplm/tools.py:371> exception=ValueError("Unknown format code 'd' for object of type 'str'")>
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/insteonplm/tools.py", line 374, in _read_line
    await self._exec_cmd(cmd)
  File "/srv/homeassistant/lib/python3.7/site-packages/insteonplm/tools.py", line 397, in _exec_cmd
    return_val = await func(arg)
  File "/srv/homeassistant/lib/python3.7/site-packages/insteonplm/tools.py", line 449, in do_connect
    await self.tools.connect(False, device=device, workdir=workdir)
  File "/srv/homeassistant/lib/python3.7/site-packages/insteonplm/tools.py", line 96, in connect
    workdir=self.workdir)
  File "/srv/homeassistant/lib/python3.7/site-packages/insteonplm/__init__.py", line 167, in create
    await conn.reconnect()
  File "/srv/homeassistant/lib/python3.7/site-packages/insteonplm/__init__.py", line 190, in reconnect
    await self._connect()
  File "/srv/homeassistant/lib/python3.7/site-packages/insteonplm/__init__.py", line 239, in _connect
    connected = await self._connect_http()
  File "/srv/homeassistant/lib/python3.7/site-packages/insteonplm/__init__.py", line 253, in _connect_http
    connected = await transport.test_connection()
  File "/srv/homeassistant/lib/python3.7/site-packages/insteonplm/__init__.py", line 362, in test_connection
    url = 'http://{:s}:{:d}/buffstatus.xml'.format(self._host, self._port)
ValueError: Unknown format code 'd' for object of type 'str'
```

**Comment by teharris1** [comment]
It will be in the next release.
