### ISSUE TITLE
Multiple monitor command line problems

### ISSUE THREAD

**Issue by TD22057** [nugget/python-insteonplm#30]
I'm using Ubuntu 14.04, python3.4, and clone of the repo on 2017/09/09 and hit several problems.  Brand new PLM USB modem and I hit it with a factory reset just to be sure it's clean.  I have 1 lamp module plugged in and linked (both directions) to the modem.

Problem 1: Run the insteonplm_monitor with -h and it throws an exception.

```
./bin/insteonplm_monitor --help
usage: insteonplm_monitor [-h] [--device DEVICE] [--verbose]

Connect to receiver and show events as they occur. Pulls the following
arguments from the command line (not method arguments): :param device: Unix
device where the PLM is attached :param verbose: Show debug logging.

optional arguments:
  -h, --help       show this help message and exit
  --device DEVICE  Device
  --verbose, -v
Task exception was never retrieved
future: <Task finished coro=<console() done, defined at /opt/homeassistant/lib/python3.4/site-packages/insteonplm/tools.py:11> exception=SystemExit(0,)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_forever
    self._run_once()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 1172, in _run_once
    handle._run()
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/opt/homeassistant/lib/python3.4/site-packages/insteonplm/tools.py", line 26, in console
    args = parser.parse_args()
  File "/usr/lib/python3.4/argparse.py", line 1737, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.4/argparse.py", line 1769, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.4/argparse.py", line 1975, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.4/argparse.py", line 1915, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.4/argparse.py", line 1843, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.4/argparse.py", line 1026, in __call__
    parser.exit()
  File "/usr/lib/python3.4/argparse.py", line 2382, in exit
    _sys.exit(status)
SystemExit: 0
```
Problem 2: Ran with no arguments and it opens /dev/ttyUSB0.  It would help if that default was in the help docs (or just make the device a required input) since my device isn't plugged in to /dev/ttyUSB0.  I have an alarmdecoder (ad2usb) module plugged in on USB0.  Yet it looks like it's reporting insteon devices and sounds like it's talking to the modem.  Note that I don't have an insteon thermostat so I'm not sure why it's reporting one.  Then it throws an exception with a message that isn't enough for me to figure out what's going on.

```
INFO:insteonplm.tools:Connecting to Insteon PLM at /dev/ttyUSB0
INFO:insteonplm.protocol:New INSTEON Device 3C.4F.C5: Thermostat (05:0b)
INFO:insteonplm.protocol:New INSTEON Device 43.AF.9B: ToggleLinc Relay (02:1a)
INFO:insteonplm.connection:Connecting to PLM on /dev/ttyUSB0
INFO:insteonplm.protocol:New callback <function console.<locals>.async_insteonplm_light_callback at 0x7eff049d3ae8> with {} (2 items already in list)
INFO:insteonplm.protocol:retroactive callback device 43.AF.9B matching {}
WARNING:insteonplm.tools:New Device: {'address_hex': '43af9b', 'capabilities': ['switch'], 'model': '2466SW', 'subcat': 26, 'product_key': None, 'description': 'ToggleLinc Relay', 'cat': 2, 'address': '43.AF.9B', 'firmware': 0}
INFO:insteonplm.protocol:retroactive callback device 3C.4F.C5 matching {}
WARNING:insteonplm.tools:New Device: {'address_hex': '3c4fc5', 'capabilities': ['climate'], 'model': '2441TH', 'subcat': 11, 'product_key': None, 'description': 'Thermostat', 'cat': 5, 'address': '3C.4F.C5', 'firmware': 0}
INFO:insteonplm.protocol:Connection established to PLM
INFO:insteonplm.protocol:Requesting PLM Info
INFO:insteonplm.protocol:Requesting First ALL-Link Record
INFO:insteonplm.tools:Are you ready to rumble?
INFO:insteonplm.tools:Relay Status
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<console() done, defined at /opt/homeassistant/lib/python3.4/site-packages/insteonplm/tools.py:11> exception=KeyError()>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/opt/homeassistant/lib/python3.4/site-packages/insteonplm/tools.py", line 134, in console
    plm.status_request(addr)
  File "/opt/homeassistant/lib/python3.4/site-packages/insteonplm/protocol.py", line 839, in status_request
    device = self.devices[address.hex]
  File "/opt/homeassistant/lib/python3.4/site-packages/insteonplm/protocol.py", line 40, in __getitem__
    raise KeyError
KeyError
```

Problem 3: Ran with the correct USB device and I got multiple exceptions, none of which I can figure out anything about.

```
 ./bin/insteonplm_monitor --device /dev/ttyUSB2
INFO:insteonplm.tools:Connecting to Insteon PLM at /dev/ttyUSB2
INFO:insteonplm.protocol:New INSTEON Device 3C.4F.C5: Thermostat (05:0b)
INFO:insteonplm.protocol:New INSTEON Device 43.AF.9B: ToggleLinc Relay (02:1a)
INFO:insteonplm.connection:Connecting to PLM on /dev/ttyUSB2
INFO:insteonplm.protocol:New callback <function console.<locals>.async_insteonplm_light_callback at 0x7fdda31f4ae8> with {} (2 items already in list)
INFO:insteonplm.protocol:retroactive callback device 3C.4F.C5 matching {}
WARNING:insteonplm.tools:New Device: {'cat': 5, 'address': '3C.4F.C5', 'address_hex': '3c4fc5', 'subcat': 11, 'model': '2441TH', 'capabilities': ['climate'], 'product_key': None, 'firmware': 0, 'description': 'Thermostat'}
INFO:insteonplm.protocol:retroactive callback device 43.AF.9B matching {}
WARNING:insteonplm.tools:New Device: {'cat': 2, 'address': '43.AF.9B', 'address_hex': '43af9b', 'subcat': 26, 'model': '2466SW', 'capabilities': ['switch'], 'product_key': None, 'firmware': 0, 'description': 'ToggleLinc Relay'}
INFO:insteonplm.protocol:Connection established to PLM
INFO:insteonplm.protocol:Requesting PLM Info
INFO:insteonplm.protocol:Requesting First ALL-Link Record
INFO:insteonplm.protocol:PLM Info from 44.85.11: category:03 subcat:15 firmware:9e
INFO:insteonplm.protocol:ALL-Link Record for 3A.29.84: flags:e2 group:01 data:01/0e/43
INFO:insteonplm.protocol:Auto Discovering device '3a2984'.
INFO:insteonplm.protocol:New INSTEON Device 3A.29.84: LampLinc Dual Band 2-pin (01:0e)
WARNING:insteonplm.tools:New Device: {'cat': 1, 'address': '3A.29.84', 'address_hex': '3a2984', 'subcat': 14, 'model': '2457D2', 'capabilities': ['light', 'dimmable'], 'product_key': None, 'firmware': 67, 'description': 'LampLinc Dual Band 2-pin'}
INFO:insteonplm.protocol:Requesting Next ALL-Link Record
INFO:insteonplm.protocol:ALL-Link Record for 3A.29.84: flags:a2 group:01 data:01/0e/43
INFO:insteonplm.protocol:Device '3a2984' is already added manually.
INFO:insteonplm.protocol:Requesting Next ALL-Link Record
INFO:insteonplm.protocol:ALL-Link database dump is complete
INFO:insteonplm.protocol:Requesting product data for 3A.29.84
INFO:insteonplm.protocol:Requesting product data for 3C.4F.C5
INFO:insteonplm.protocol:Requesting product data for 43.AF.9B
INFO:insteonplm.protocol:Failed to discover device '3c4fc5'.
INFO:insteonplm.protocol:Failed to discover device '43af9b'.
INFO:insteonplm.protocol:Polling all devices in ALDB
INFO:insteonplm.protocol:Requesting status for 3A.29.84
INFO:insteonplm.protocol:Requesting status for 3C.4F.C5
INFO:insteonplm.protocol:Requesting status for 43.AF.9B
INFO:insteonplm.protocol:INSTEON standard 3A.29.84->44.85.11: cmd1:03 cmd2:00 flags:20
ERROR:asyncio:Exception in callback PLM._parse_insteon_standard(address: 3A.2..., flagsval: 32)
handle: <Handle PLM._parse_insteon_standard(address: 3A.2..., flagsval: 32)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/opt/homeassistant/lib/python3.4/site-packages/insteonplm/protocol.py", line 525, in _parse_insteon_standard
    self._parse_product_data_response(msg.address, msg.userdata)
  File "/opt/homeassistant/lib/python3.4/site-packages/insteonplm/protocol.py", line 640, in _parse_product_data_response
    category = userdata[4]
IndexError: bytearray index out of range
INFO:insteonplm.tools:Are you ready to rumble?
INFO:insteonplm.tools:Relay Status
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<console() done, defined at /opt/homeassistant/lib/python3.4/site-packages/insteonplm/tools.py:11> exception=KeyError()>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/opt/homeassistant/lib/python3.4/site-packages/insteonplm/tools.py", line 134, in console
    plm.status_request(addr)
  File "/opt/homeassistant/lib/python3.4/site-packages/insteonplm/protocol.py", line 839, in status_request
    device = self.devices[address.hex]
  File "/opt/homeassistant/lib/python3.4/site-packages/insteonplm/protocol.py", line 40, in __getitem__
    raise KeyError
KeyError
```

Digging around in the code, it looks like the lamp and thermostat are hard coded in tools.py:140.  Why is that?

**Comment by dakoellis** [comment]
I've been having the same problem.  Running Arch and Python 3.6, with a PLM Serial modem.  Would love to get this to work instead of the hub but nothin' doin' with this or hass
